name: Windows CI build

on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

permissions:
  contents: write

jobs:
# MAUI Windows Build
  build-windows:
    runs-on: windows-latest
    name: Windows Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui-windows --ignore-failed-sources
          dotnet workload list

      - name: Build MAUI Windows
        run: |
          dotnet build Mauibench.csproj -c Release -f net9.0-windows10.0.19041.0
  
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: v1.0.0