name: CI build

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    name: Windows Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui-windows --ignore-failed-sources
          dotnet workload list

      - name: Dotnet Workload Restore
        run: |
          dotnet workload restore Mauibench.csproj

      - name: Build MAUI Windows
        run: |
          dotnet build Mauibench.csproj -c Release -f net10.0-windows10.0.19041.0

  build-macos:
    runs-on: macos-26
    name: macOS Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui --ignore-failed-sources
          dotnet workload install macos --ignore-failed-sources
          dotnet workload list

      - name: Dotnet Workload Restore
        run: |
          dotnet workload restore Mauibench.csproj

      - name: Show Xcode info
        run: |
          xcode-select -p
          xcodebuild -version
          xcodebuild -showsdks

      - name: Select Xcode 26
        run: sudo xcode-select -s /Applications/Xcode_26.2.app

      - name: Build MAUI macOS
        run: |
          dotnet build Mauibench.csproj -c Release -f net10.0-maccatalyst
          
  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: v1.0.3
